<JSON-text> ::= <ws> <value> <ws>

<ws> ::= "" | " " | "\n" | "\t" | "\r" | <ws> <ws>

<value> ::= "null" | "false" | "true" | <object> | <array> | <number> | <string>

<array> ::= "[" <ws> <element> <ws> "]" | "[" <ws> "]"
<element> ::= <value> | <element> <ws> "," <ws> <value>

<object> ::= "{" <ws> <element> <ws> "}" | "{" <ws> "}"
<member> ::= <string> <ws> ":" <ws> <value> | <member> <ws> "," <ws> <string> <ws> ":" <ws> <value>

<number> ::= <minus> <int_or_zero> <frac> <exp>
<minus> ::= "-" | ""
<int_or_zero> ::= "0" | <int_without_zero>
<int_without_zero> ::= "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | <int_without_zero> <int>
<int> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | <int> <int>
<frac> ::= "" | "." <int>
<plus_minus> ::= "" | "+" | "-"
<e> ::= "e" | "E"
<exp> ::= "" | <e> <plus_minus> <int>

<string> ::= '"' <char> '"'
<hex> ::= "0"| "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "a" | "b" | "c" | "d" | "e" | "f" | "A" | "B" | "C" | "D" | "E" | "F"
<char> ::= "" | <char> <char> | '\"' | '\/' | '\\' | '\b' | '\f' | '\n' | '\r' | '\t' | '\u' <hex> <hex> <hex> <hex>
